fix: Define a `staticfiles` storage setting
Problem:
System check failure due to improperly configured settings.

Error:
SystemCheckError: System check identified some issues:

ERRORS:
```
?: (staticfiles.E005) The STORAGES setting must define a 'staticfiles' storage.
```

Fix:
Given the override of `STORAGES`,
Provide config to define a staticfiles storage backend.