fix: Isolate setting to resolve env side effects
[Problem]
Django application does not start due to the following error:
```
ImproperlyConfigured: WSGI application '<project>.config.wsgi.application' could not be loaded;
Error importing module.
```

This error was caused by the following error:
```
ModuleNotFoundError: No module named 'debug_toolbar'
```

[Cause]
`ENABLE_DEBUG_TOOLBAR` setting was defined in an target setting.
Each import of the setting implicitly applied the settings of
the develop module. This caused the launch failure in non-develop
targets, where `debug_toolbar` settings where applied in an env
where the dependency was not installed.

[Fix]
Migrate and isolate setting `ENABLE_DEBUG_TOOLBAR` to non-environment
specific module to avoid side effects where develop settings
are applied in the wrong context.

[Note]
- The constants module probably isn't the best place to keep the setting
  but it will do for now.